### PR TITLE
Added NEBA reference

### PR DESCRIPTION
**Pull request by al-dexter**
Added reference to [NEBA](http://neba.io/)

### CODE REVIEW

**Comment by paulrohrbeck** [comment]
Hey, thanks for contributing. Could you resolve the conflict and submit again?

**Comment by al-dexter** [comment]
Hey Paul,

I don't see any conflicts.. What do you mean exactly?

**Comment by paulrohrbeck** [comment]
Sorry, I haven't had the chance to look in detail but Github doesn't let me cleanly merge this online. I was hoping it's something you can fix easily on your end by pulling again.

**Comment by al-dexter** [comment]
Ok, sorry, my fork was out of sync, now the conflict is resolved.

**Pull request merged**
